baseURL = "http://www.freesurfing.net/"
languageCode = "zh-cn"
defaultContentLanguage = "en-us"

title = "自由小站"
theme = "journal"
[permalinks]
  post = "/:year/:month/:title/"

[author]
  name = "Jackson Jia"
  homepage = "http://www.freesurfing.net/"

[params]
  description = "Blog meta description."
  githubUsername = "JacksonJia"
  tagline = ""
#[params.work]
#  jobTitle = "occupation"
#  company = "LingmiaoTech"
#  companyUrl = "http://www.echocloud.com/"
